### ISSUE TITLE
SDM630 support

### ISSUE THREAD

**Issue by Vollstrecker-2015** [christian1980nrw/VenusOS-SDM72D-M-V2-Eastron-Modbus-driver#1]
Great job, thanks for your efforts.

I  have adopted the code for my SDM630 meter, which is not too complicated, since it uses the same registers.

However, I have the same issues with the VRM portal, and I have to admit that I am not clever enough to apply the changes in the code which come into my mind to fix that. So if the problems are solved I'd like to provide the modified code for a SDM630 meter.

**Comment by butterwecksolutions** [comment]
Hi, i am still testing, i am updating it almost daily until i am happy with the VRM results.
Its not easy because i didnt find a good documentation, so it is only possible to find it out by try and error.

**Comment by Vollstrecker-2015** [comment]
Keep going!

I wanted to check if it works when reading the forward and reverse energies for L1, L2 and L3 and then calculating the total and net energy from those numbers.
Unfortunately I didn't get the code working.
It would be great if the SDM meters are working without compromises.

**Comment by butterwecksolutions** [comment]
I think it is working now. But i used Register 0x018C (look at the code).
I think this register exists only at the SDM72 V2.

see https://github.com/reaper7/SDM_Energy_Meter/blob/master/SDM.h#L202

So with your SDM630 meter you have to use L1, L2, L3 instead of L1 like i did with my SDM72 V2.
L1_IMPORT_ACTIVE_ENERGY                   0x015A                    //  kWh     
L2_IMPORT_ACTIVE_ENERGY                   0x015C                    //  kWh
L3_IMPORT_ACTIVE_ENERGY                   0x015E                    //  kWh
L1_EXPORT_ACTIVE_ENERGY                   0x0160                    //  kWh
L2_EXPORT_ACTIVE_ENERGY                   0x0162                    //  kWh
L3_EXPORT_ACTIVE_ENERGY                   0x0164                    //  kWh
